load("@fbcode_macros//build_defs:build_file_migration.bzl", "fbcode_target", "non_fbcode_target")
# Copyright (c) Meta Platforms, Inc. and affiliates.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree.

load("@fbsource//xplat/executorch/build:runtime_wrapper.bzl", "runtime")

oncall("executorch")

fbcode_target(_kind = runtime.python_test,
    name = "test_builder",
    srcs = ["test_builder.py"],
    deps = [
        "//executorch/extension/llm/export:export_lib",
        "//caffe2:torch",
    ],
)

fbcode_target(_kind = runtime.python_test,
    name = "test_export_composable_attention",
    srcs = ["test_export_composable_attention.py"],
    deps = [
        "//caffe2:torch",
        "//executorch/exir:lib",
        "//executorch/extension/llm/export:export_composable_attention_lib",
    ],
)

fbcode_target(_kind = runtime.python_test,
    name = "test_probe_composable_attention_widths",
    srcs = ["test_probe_composable_attention_widths.py"],
    deps = [
        "//executorch/extension/llm/export:probe_composable_attention_widths_lib",
    ],
)

fbcode_target(_kind = runtime.python_test,
    name = "test_int4",
    srcs = ["test_int4.py"],
    deps = [
        "//caffe2:torch",
        "//executorch/extension/llm/export:int4",
        "//pytorch/ao:torchao",
    ],
)

fbcode_target(_kind = runtime.python_test,
    name = "test_gguf",
    srcs = ["test_gguf.py"],
    deps = [
        "//caffe2:torch",
        "//executorch/extension/llm/export:gguf",
        "fbsource//third-party/pypi/gguf:gguf",
        "fbsource//third-party/pypi/numpy:numpy",
    ],
)
